global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'coredrain'
    static_configs:
      - targets: ['app:9464']
    scrape_interval: 5s
    metrics_path: /metrics
